name: Build and deploy ASP.NET Core app to Azure Web App - learningapp204

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust version as needed

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the application
      - name: Build the application
        run: dotnet build --configuration Release

      # Step 5: Publish the application to the output folder
      - name: Publish the application
        run: dotnet publish --configuration Release --property:PublishDir=${{ github.workspace }}/publish

      # Step 6: Upload the published output as an artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ${{ github.workspace }}/publish/
  
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT token

    steps:
      # Step 1: Download the artifact generated in the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F1B95AD3E3448E58C542AB34B4F6FDD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0319ED9CD5C446CDA5D527CF624EB669 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B6A3224E5984439A4B789B6B2C760C6 }}

      # Step 3: Deploy the artifact to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'learningapp204'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
